### ISSUE TITLE
Emojify not returning 0

### ISSUE THREAD

**Issue by MirayXS** [LandenStephenss/xCubed#10]
The emojify command doesn't return a 0 number. 

_ex.._ `x!emojify 1234567890`
 Attachment:
![image](https://user-images.githubusercontent.com/55494819/70855029-4055a780-1ec4-11ea-9658-81993dd7183c.png)

_P.S._ i'm not able to fix this. I tried to do some changes but none of them works

**Comment by MirayXS** [comment]
![image](https://user-images.githubusercontent.com/55494819/70855038-71ce7300-1ec4-11ea-9c21-cef897679658.png)

**Comment by LandenStephenss** [comment]
I will look into this or have Flag look into this. It will be fixed in V8

**Comment by LandenStephenss** [comment]
https://why-am-i-he.re/QFhOmE.png simple fix
