### ISSUE TITLE
+31% of Issues (according to codacy.com)

### ISSUE THREAD

**Issue by MirayXS** [LandenStephenss/xCubed#12]
the project as **_+31% of issues_** because of some code-style in makeBoxLetters.js.

Just copy-paste.
```
function makeBoxLetter(word) {
    const numbers = [
          "one",
          "two",
          "three",
          "four",
          "five",
          "six",
          "seven",
          "eight",
          "nine",
          "zero"
    ];
    return word.replace(/\w/g, (w) => `:${isNaN(w) ? `regional_indicator_${w}` : numbers[w - 1]}:`);
}

module.exports = makeBoxLetter;
```
fixes:
Strings must use doublequotes
Missing semicolons

**Comment by LandenStephenss** [comment]
Hey! I’m currently working on V8 of xCubed. You can check progress on the bot in the discord server. Although sadly i am going to be keeping it closed source . Here is the invite URL for the server if you’d like to join https://discord.gg/kQUpSgw
